extends layouts/default
block title
    title Create Dockerfile - DoConfig, Create Config in Seconds

block content
    .createconf
        //- subheader
        - 
            let title = 'Create Dockerfile'
            let description = 'Docker can build images automatically by reading the instructions from a Dockerfile. A Dockerfile is a text document that contains all the commands a user could call on the command line to assemble an image. Using docker build users can create an automated build that executes several command-line instructions in succession.'
            let link_url = 'https://docs.docker.com/engine/reference/builder/'
            let link_text = 'More about Dockerfile'
        include components/subheader-conf

        section
            .container
                .grid
                    .col-12
                        .createconf-form 
                            .createconf-form-control
                                label Images 
                                input(type='text' placeholder='for example: ubuntu, nodejs-slim')
                                small Images is based on 
                                    a(href="https://hub.docker.com/" target="_blank") Docker Hub

                            .createconf-form-control.commands-form-control
                                label Command to execute 
                                input(type='text' placeholder='for example: apt-get update -y')

                                //- list setup command
                                .commands.active
                                    each n in ['apt-get update -y && apt-get autoremove -y', 'apt-get install -y supervisor', 'apt-get autoremove -y', 'build ./cfg/maxready', 'powerless infrared -p mask']
                                        .command
                                            | #{n}
                                small Make sure to write command in sequentially
                            
                            //- sample empty command 
                            .createconf-form-control.commands-form-control
                                label Command to execute (sample if empty)
                                input(type='text' placeholder='for example: apt-get update -y')

                                .commands.active
                                small Make sure to write command in sequentially
                                    
